/* eslint-disable @next/next/no-img-element */
import Container from '@core/Container'
import Timeline from '@components/Timeline'
import Carousel from '@components/Carousel'
import DivideY from '@core/Divide/Divide'
import Contact from '@components/Contact'
import Header from '@components/Header'
import Image from 'next/image'
import React from 'react'
import Head from 'next/head'

import { experience, projects } from '@utils/config'

export default function Home() {
  return (
    <>
      <Head>
        <title>Samara Carvalho - Developer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.svg" />
      </Head>

      <Header />

      <DivideY>
        <Container
          id="about-me"
          className="mt-36 w-full flex flex-col-reverse md:flex-row items-center space-x-6"
        >
          <div className="space-y-6">
            <span>
              <h1 className="text-4xl md:text-6xl font-bold">
                Samara Carvalho
              </h1>
              <p className="text-xl">Front-end Developer</p>
            </span>

            <p className="text-xl">
              Densenvolvedora apaixonada em aprender novas habilidades e
              enfrentar desafios que podem me impulsionar a outros níveis 🚀
            </p>

            <p className="text-xl">
              Tenho como especialidade frontend, mas também possuo conhecimento
              em desenvolvimento backend e mobile 💜
            </p>
          </div>

          <Image
            src="/sam.png"
            alt="Samara Carvalho"
            sizes="100%"
            width={360}
            height={360}
            className="hidden md:block"
          />
        </Container>

        <Container className="w-full">
          <Timeline id="experience" title="Experience" data={experience} />
        </Container>

        <Container className="w-full">
          <Carousel id="projects" title="Projects" data={projects} />
        </Container>

        <Container id="technologies" className="w-full">
          <h4 className="text-3xl font-bold">Technologies</h4>

          <div className="backdrop-blur-md rounded-lg mt-6">
            <img
              src="https://skillicons.dev/icons?i=html,css,js,ts,react,next,nodejs,tailwind,materialui,docker,mongodb,prisma,figma,git,redux,sass,graphql,firebase&perline=9"
              alt="Technologies"
            />
          </div>
        </Container>

        {/* <Container className="w-full border-l-2 border-pink-500">
          <p>Se falhar, tente novamente! A disciplina vence o talento.</p>
        </Container> */}

        <Container
          id="contact"
          className="w-full flex flex-row justify-between space-x-6"
        >
          <Contact />
        </Container>
      </DivideY>
    </>
  )
}
