/* eslint-disable @next/next/no-img-element */
import Container from '@core/Container'
import Timeline from '@components/Timeline'
import Carousel from '@components/Carousel'
import DivideY from '@core/Divide/Divide'
import Contact from '@components/Contact'
import Header from '@components/Header'
import React from 'react'
import Head from 'next/head'

import { experience, projects } from '@utils/config'
import { animated, useInView } from '@react-spring/web'
import { config, transitionY } from '@utils/spring'

export default function Home() {
  const [refTechnologies, springsTechnologies] = useInView(
    () => transitionY,
    config
  )

  const [refContact, springsContact] = useInView(() => transitionY, config)
  const [refAbout, springsAbout] = useInView(() => transitionY, config)

  return (
    <>
      <Head>
        <title>Samara Carvalho - Developer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.svg" />
      </Head>

      <Header />

      <DivideY>
        <Container
          id="about-me"
          className="mt-16 md:mt-36 w-full flex flex-col-reverse md:flex-row items-center md:space-x-6"
        >
          <animated.div
            style={springsAbout}
            ref={refAbout}
            className="space-y-6"
          >
            <span>
              <h1 className="text-4xl md:text-6xl font-bold">
                Samara Carvalho
              </h1>
              <p className="text-xl">Front-end Developer</p>
            </span>

            <p className="text-xl">
              Developer passionate about learning new skills and facing
              challenges that can push me to new levels 🚀
            </p>

            <p className="text-xl">
              My specialty is frontend, but I also have knowledge in backend and
              mobile development 💜
            </p>
          </animated.div>

          <animated.img
            style={springsAbout}
            ref={refAbout}
            src="/sam.png"
            alt="Samara Carvalho"
            sizes="100%"
            width={360}
            height={360}
            className="max-md:scale-75"
          />
        </Container>

        <Container id="experience" className="w-full">
          <Timeline title="Experience" data={experience} />
        </Container>

        <Container id="projects" className="w-full">
          <Carousel title="Projects" data={projects} />
        </Container>

        <Container id="technologies" className="w-full">
          <animated.div style={springsTechnologies} ref={refTechnologies}>
            <h4 className="text-3xl font-bold">Technologies</h4>

            <div className="backdrop-blur-md rounded-lg mt-6">
              <img
                src="https://skillicons.dev/icons?i=html,css,js,ts,react,next,nodejs,tailwind,materialui,docker,mongodb,prisma,figma,git,redux,sass,graphql,firebase&perline=9"
                alt="Technologies"
              />
            </div>
          </animated.div>
        </Container>

        <Container id="contact" className="w-full">
          <animated.div
            className="w-full flex flex-row justify-between space-x-6"
            style={springsContact}
            ref={refContact}
          >
            <Contact />
          </animated.div>
        </Container>
      </DivideY>
    </>
  )
}
